// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYaTb8E3CYauAoUFUYHDZa8SBqt0yMMQo',
    appId: '1:890531713471:web:95ca3fafeb84dae82b510a',
    messagingSenderId: '890531713471',
    projectId: 'tiktok-clone-81159',
    authDomain: 'tiktok-clone-81159.firebaseapp.com',
    storageBucket: 'tiktok-clone-81159.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQXHBKVsNIzzUbeFu04kzcMPj6CxaOA1o',
    appId: '1:890531713471:android:c43e70179beddb452b510a',
    messagingSenderId: '890531713471',
    projectId: 'tiktok-clone-81159',
    storageBucket: 'tiktok-clone-81159.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAueHuxItbABBlrnfaWIYBQWSaerbjAEo',
    appId: '1:890531713471:ios:24e3188af1dbea2a2b510a',
    messagingSenderId: '890531713471',
    projectId: 'tiktok-clone-81159',
    storageBucket: 'tiktok-clone-81159.appspot.com',
    iosBundleId: 'com.example.tiktok',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAueHuxItbABBlrnfaWIYBQWSaerbjAEo',
    appId: '1:890531713471:ios:24e3188af1dbea2a2b510a',
    messagingSenderId: '890531713471',
    projectId: 'tiktok-clone-81159',
    storageBucket: 'tiktok-clone-81159.appspot.com',
    iosBundleId: 'com.example.tiktok',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYaTb8E3CYauAoUFUYHDZa8SBqt0yMMQo',
    appId: '1:890531713471:web:049b62581a3e6e2f2b510a',
    messagingSenderId: '890531713471',
    projectId: 'tiktok-clone-81159',
    authDomain: 'tiktok-clone-81159.firebaseapp.com',
    storageBucket: 'tiktok-clone-81159.appspot.com',
  );
}
